### ISSUE TITLE
trying to complie 'FilenameUtils' not found.

### ISSUE THREAD

**Issue by LiteWinOS** [himselfv/manifestenum#15]
[dcc64 Fatal Error] AssemblyDb.Bundles.pas(127): F2613 Unit 'FilenameUtils' not found.

**Comment by himselfv** [comment]
Hi! It only needed AppFolder() from there, I've moved it to OsUtils (from CBSEnum, which is needed to compile this) and removed references to FilenameUtils (and UniStrUtils).
